# Generated by Django 4.1.12 on 2023-10-30 14:10

import app.data_validation_fun
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_custom_usermodel_profile_picture_users_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_usermodel',
            name='profile_picture',
            field=models.ImageField(default='default-img/unknown.jpg', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg']), app.data_validation_fun.Data_validation.img_validation]),
        ),
        migrations.AlterField(
            model_name='users_task',
            name='task_description',
            field=models.TextField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='users_task',
            name='task_title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
